### ISSUE TITLE
jar包问题

### ISSUE THREAD

**Issue by hungryquiter** [hucheng91/freemarker_xdoxreport#1]
你好，我想问下你的这里都用了什么包，我用的时候总是报错
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.POIXMLDocumentPart.getPackageRelationship()Lorg/apache/poi/openxml4j/opc/PackageRelationship;
	at org.apache.poi.xwpf.converter.core.styles.XWPFStylesDocument.getFontsDocument(XWPFStylesDocument.java:1481)
	at org.apache.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:192)
	at org.apache.poi.xwpf.converter.core.styles.XWPFStylesDocument.<init>(XWPFStylesDocument.java:186)
	at org.apache.poi.xwpf.converter.core.XWPFDocumentVisitor.createStylesDocument(XWPFDocumentVisitor.java:161)
	at org.apache.poi.xwpf.converter.core.XWPFDocumentVisitor.<init>(XWPFDocumentVisitor.java:154)
	at org.apache.poi.xwpf.converter.pdf.internal.PdfMapper.<init>(PdfMapper.java:149)
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:54)
	at org.apache.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:37)
	at org.apache.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:45)
	at com.havenliu.document.XMlToDoc.makePdfByXcode(XMlToDoc.java:82)
	at com.havenliu.document.XMlToDoc.main(XMlToDoc.java:24)

**Comment by hucheng91** [comment]
你把我这个maven项目clone下去没有，应该不会出现这个错误的，还有你用的word是那个版本，是doc，还是docx，这个必须得是docx

**Comment by csj-libs** [comment]
java.lang.NoSuchMethodError: No virtual method getPackageRelationship()Lorg/apache/poi/openxml4j/opc/PackageRelationship; in class Lorg/apache/poi/POIXMLDocumentPart; or its super classes (declaration of 'org.apache.poi.POIXMLDocumentPart' appears in /data/app/com.lj.zmplugin-1/split_lib_dependencies_apk.apk:classes34.dex)

**Comment by dwfbenben** [comment]
@hungryquiter：我这也碰到同样的问题，你那里解决了吗?

**Comment by hucheng91** [comment]
docx
